[build]
builder = "NIXPACKS"

[deploy]
# We remove the cd backend part because Railway is already inside that folder
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
